### ISSUE TITLE
TrueNAS-SCALE-22.12.1 changes to their MIB file

### ISSUE THREAD

**Issue by rdoac** [mkorthof/check_truenas#1]
This script is no longer working on the latest (.1) update as they made significant changes to their MIB. 

I got basic health back.  I am not convinced that reporting OK on size is working.

```
diff check_truenas check_truenas.old 
7,9c7,9
< # - snmpwalk -v2c -c public 10.1.1.2 -m /usr/share/snmp/mibs/FREENAS-MIB.txt zpoolName
< #     zpoolName.1 = STRING: boot-pool
< #     zpoolName.2 = STRING: tank
---
> # - snmpwalk -v2c -c public 10.1.1.2 -m /usr/share/snmp/mibs/FREENAS-MIB.txt zpoolDescr
> #     zpoolDescr.1 = STRING: boot-pool
> #     zpoolDescr.2 = STRING: tank
109c109
<   idx="$( func_idx "$ZPOOL" "zpoolName" )"
---
>   idx="$( func_idx "$ZPOOL" "zpoolDescr" )"
111c111
<   if echo "$health" | \grep -q "ONLINE"; then
---
>   if echo "$health" | \grep -q "online"; then
126c126
<   zp_idx="$( func_idx "$ZPOOL" "zpoolName" )"
---
>   zp_idx="$( func_idx "$ZPOOL" "zpoolDescr" )"
```

**Comment by rdoac** [comment]
`zpoolAllocationUnits.2: Unknown Object Identifier (Sub-id not found: (top) -> zpoolAllocationUnits)
zpoolAvailable.2: Unknown Object Identifier (Sub-id not found: (top) -> zpoolAvailable)
zpoolUsed.2: Unknown Object Identifier (Sub-id not found: (top) -> zpoolUsed)
zpoolSize.2: Unknown Object Identifier (Sub-id not found: (top) -> zpoolSize)
datasetAllocationUnits.4: Unknown Object Identifier (Sub-id not found: (top) -> datasetAllocationUnits)
datasetAvailable.4: Unknown Object Identifier (Sub-id not found: (top) -> datasetAvailable)
datasetAllocationUnits.4: Unknown Object Identifier (Sub-id not found: (top) -> datasetAllocationUnits)
datasetUsed.4: Unknown Object Identifier (Sub-id not found: (top) -> datasetUsed)
datasetAllocationUnits.6: Unknown Object Identifier (Sub-id not found: (top) -> datasetAllocationUnits)
datasetUsed.6: Unknown Object Identifier (Sub-id not found: (top) -> datasetUsed)
datasetAllocationUnits.17: Unknown Object Identifier (Sub-id not found: (top) -> datasetAllocationUnits)
datasetUsed.17: Unknown Object Identifier (Sub-id not found: (top) -> datasetUsed)
USAGE OK - `

**Comment by mkorthof** [comment]
Don't know if the MIB changed, but there was an issue with sed.

**Comment by mkorthof** [comment]
Just compared the v13 MIB with the one they used for v12, all changes are related to network interfaces only.
And make sure you specifiy mib location if needed (e.g.  `-m /usr/local/share/snmp/mibs/FREENAS-MIB.txt`)
Also this check is for **CORE**, not SCALE. I never tested the latter, thats a newer & diff product based on linux I believe. Could be this is not going to work at all.
